Repository codestates-seb/seb40_main_011, pull requests merged in 2022-11, with the labels that each got.

#16 Feat/be 11 auditing
  server/src/main/java/seb/project/Codetech/CodetechApplication.java
  server/src/main/java/seb/project/Codetech/global/auditing/BaseTime.java
Labels: Back, 기능추가

#18 Feat/be 8 question
  server/src/main/java/seb/project/Codetech/question/entity/Answer.java
  server/src/main/java/seb/project/Codetech/question/entity/question.java
Labels: Back, 기능추가

#19 feat: Answer 엔티티 작성
  server/src/main/java/seb/project/Codetech/question/entity/Answer.java
  server/src/main/java/seb/project/Codetech/question/entity/question.java
Labels: Back, 기능추가

#20 feat: SnackReview 엔티티 작성
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
Labels: Back, 기능추가

#40 [Feat] 더미데이터 업데이트
  client/data/data.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/Member.tsx
  client/src/components/Header/Header.tsx
  client/src/components/List/ProductList.tsx
  client/src/index.tsx
  client/src/pages/Main.tsx
  client/src/util/useFetch.tsx
  client/tailwind.config.js
Labels: Front, 리펙토링

#42 Feat/seongho/score #34
  server/src/main/java/seb/project/Codetech/jpa/converter/ScoreJsonConverter.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
Labels: Back, 기능추가

#48 feat: SignUp 페이지 레이아웃 css 구현 #28
  client/src/App.tsx
  client/src/components/Buttons/SignUp.tsx
  client/src/components/common.css
  client/src/pages/SignUpPage.tsx
Labels: Front, 레이아웃

#52 [feat] SnackReviewController 초안 작성
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewPatchDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewPostDto.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
  server/src/main/java/seb/project/Codetech/snackreview/validation/annotation/ValidScore.java
  server/src/main/java/seb/project/Codetech/snackreview/validation/validator/ScoreValidator.java
  server/src/test/java/seb/project/Codetech/snackreview/entity/SnackReviewTest.java
Labels: Back, 기능추가

#51 [Feat] CI/CD 테스트를 위한 PR (#50)
  server/build.gradle
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/entity/FileEntity.java
  server/src/main/java/seb/project/Codetech/file/repository/FileRepository.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/product/entity/Type.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/upload.html
Labels: Back, 기능추가, 테스트

#54 feat: 마이페이지 레이아웃 CSS 구현
  client/src/App.tsx
  client/src/components/Footer/Member.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/pages/MyPage.tsx
Labels: Front, 기능추가, 레이아웃

#55 refactor: ScoreJsonConverter global/converter 패키지로 이동 (#53)
  server/src/main/java/seb/project/Codetech/global/converter/ScoreJsonConverter.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
Labels: Back, 리펙토링

#56 feat:Toast UI 에디터, 뷰어컴포넌트 구현
  client/src/App.tsx
  client/src/components/Buttons/AddPost.tsx
  client/src/components/Buttons/SignUp.tsx
  client/src/components/Selectors/CategorieSelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/components/common.css
  client/src/pages/WriteReview.tsx
Labels: Front, 기능추가, 레이아웃

#57 fix: 연관관계 메소드 수정
  server/src/main/java/seb/project/Codetech/discount/entity/Discount.java
  server/src/main/java/seb/project/Codetech/discount/entity/DiscountComment.java
  server/src/main/java/seb/project/Codetech/question/entity/Answer.java
  server/src/main/java/seb/project/Codetech/question/entity/Question.java
  server/src/main/java/seb/project/Codetech/recommend/entity/Recommend.java
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
  server/src/main/java/seb/project/Codetech/user/entity/User.java
Labels: Back, 수정

#61 style: 회원가입 CSS 수정#60
  client/package-lock.json
  client/src/components/Buttons/SignUp.tsx
  client/src/components/common.css
  client/src/pages/SignUpPage.tsx
Labels: Front, 레이아웃, 수정

#63 feat: 마이페이지 리뷰탭 구현
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
Labels: Front, 기능추가, 레이아웃

#64 fix: 전반적인 파일 업로드 시스템 개선및 일부 설정 변경
  server/src/main/java/seb/project/Codetech/file/entity/FileEntity.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application.yml
Labels: Back, 리펙토링, 수정, 테스트

#67 feat: 마이페이지 모달 레이아웃 구현
  client/src/App.tsx
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/common.css
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
Labels: Front, 기능추가, 레이아웃

#72 feat: SnackReview 기본 CRUD 구현
  server/src/main/java/seb/project/Codetech/global/mapper/GenericControllerMapper.java
  server/src/main/java/seb/project/Codetech/global/mapper/GenericServiceMapper.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewControllerV1.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewControllerDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewPatchDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewPostDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewServiceDto.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewControllerMapper.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/SnackReviewSimpleRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
  server/src/main/java/seb/project/Codetech/snackreview/validation/annotation/ValidScore.java
Labels: Back, 기능추가

#73 fix: 파일 서비스 예외 처리 개선 (#36)
  server/build.gradle
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewDto.java
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application.yml
Labels: Back, 기능추가, 수정

#74 Feat: SignUp 페이지 기능 구현 #62
  client/data/data.json
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/components/common.css
  client/src/pages/SignUpPage.tsx
  client/src/pages/WriteReview.tsx
Labels: Front, 기능추가

#76 merge: 파일 서비스 기능 구현 완료 (#36)
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/entity/FileEntity.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/product/entity/Product.java
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/user/entity/User.java
  server/src/main/resources/templates/upload.html
Labels: Back, 기능추가, 리펙토링, 배포, 수정, 테스트

#80 chore: querydsl 의존성 추가 (#78)
  server/build.gradle
Labels: Back, 기능추가

#81 feat: MainPage 카테고리 기능구현
  client/data/data.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Details/ReviewDetail.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/List/BestReviewList.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/List/ReviewList.tsx
  client/src/components/Selectors/MainCategory.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/pages/Main.tsx
  client/src/pages/ReviewDetail.tsx
  client/src/types/mainPageTypes.tsx
  client/tailwind.config.js
Labels: Front

#83 feat: 스낵리뷰 조회 쿼리 구현
  server/src/main/java/seb/project/Codetech/global/converter/ScoreJsonConverter.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewControllerDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewServiceDto.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/Score.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/SnackReviewRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
  server/src/main/java/seb/project/Codetech/snackreview/validation/validator/ScoreValidator.java
Labels: Back, 기능추가

#85 feat: 리뷰리스트 레이아웃 CSS
  client/package-lock.json
  client/src/App.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/components/Review/StarRating.tsx
  client/src/pages/ReviewDetail.tsx
  client/src/pages/ReviewLists.tsx
Labels: Front, 기능추가, 레이아웃

#87 feat: 서버 오픈으로 인한 서버 인스턴스 추가
  client/data/data.json
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Details/CommentInput.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/List/BestReviewList.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/List/ReviewList.tsx
  client/src/components/QuestionList/QuestionInput.tsx
  client/src/components/Selectors/MainCategory.tsx
  client/src/pages/QuestionLists.tsx
  client/src/types/mainPageTypes.tsx
  client/src/util/ServerApiCollection.tsx
  client/src/util/apiCollection.tsx
  client/src/util/axiosInstance.tsx
  client/src/util/testApiCollection.tsx
Labels: Front, 기능추가

#89 feat: 리뷰작성페이지 기능추가#75
  client/src/App.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/pages/SignUpPage.tsx
  client/src/pages/WriteReview.tsx
  client/src/store/review.tsx
Labels: Front, 기능추가

#95 fix: 일부 설정 개선
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductDto.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/entity/Product.java
  server/src/main/java/seb/project/Codetech/product/mapper/ProductMapper.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application.yml
Labels: Back, 기능추가

#99 feat: Question 도메인 CUD 구현
  server/src/main/java/seb/project/Codetech/global/config/SecurityConfiguration.java
  server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java
  server/src/main/java/seb/project/Codetech/question/controller/AnswerController.java
  server/src/main/java/seb/project/Codetech/question/controller/QuestionController.java
  server/src/main/java/seb/project/Codetech/question/dto/AnswerRequestDto.java
  server/src/main/java/seb/project/Codetech/question/dto/AnswerServiceDto.java
  server/src/main/java/seb/project/Codetech/question/entity/Answer.java
  server/src/main/java/seb/project/Codetech/question/entity/Question.java
  server/src/main/java/seb/project/Codetech/question/mapper/AnswerControllerMapper.java
  server/src/main/java/seb/project/Codetech/question/mapper/AnswerServiceMapper.java
  server/src/main/java/seb/project/Codetech/question/respository/AnswerRepository.java
  server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepository.java
  server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/question/respository/QuestionRepository.java
  server/src/main/java/seb/project/Codetech/question/service/AnswerService.java
  server/src/main/java/seb/project/Codetech/question/service/QuestionService.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewControllerMapper.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
  server/src/main/java/seb/project/Codetech/user/entity/User.java
Labels: Back, 기능추가

#103 예외처리 누락으로 인한 PR
  server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java
Labels: 수정

#104 feat: 질문 채택, 질문 조회 API 구현
  server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java
  server/src/main/java/seb/project/Codetech/question/controller/AnswerController.java
  server/src/main/java/seb/project/Codetech/question/controller/QuestionController.java
  server/src/main/java/seb/project/Codetech/question/dto/QuestionRequestDto.java
  server/src/main/java/seb/project/Codetech/question/dto/QuestionResponseDto.java
  server/src/main/java/seb/project/Codetech/question/entity/Answer.java
  server/src/main/java/seb/project/Codetech/question/entity/Question.java
  server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepository.java
  server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/question/service/AnswerService.java
  server/src/main/java/seb/project/Codetech/question/service/QuestionService.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
  server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
Labels: Back, 기능추가

#106 feat: 리뷰리스트 별점기능 구현
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/QuestionList/QuestionInput.tsx
  client/src/components/Review/CreatSnackReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/components/Review/StarRating.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/ReviewLists.tsx
  client/src/util/ServerApiCollection.tsx
Labels: Front, 기능추가, 레이아웃

#117 feat: 제품 통계 레디스에 저장 구현
  server/src/main/java/seb/project/Codetech/global/config/RedisConfig.java
  server/src/main/java/seb/project/Codetech/redis/config/RedisConfig.java
  server/src/main/java/seb/project/Codetech/redis/entity/ProductStat.java
  server/src/main/java/seb/project/Codetech/redis/repository/ProductStatRepository.java
  server/src/main/java/seb/project/Codetech/redis/service/ProductStatService.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
Labels: Back, 기능추가

#129 feat: 마이페이지 프로필 API 연동
  client/src/App.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/Review/CreatSnackReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/pages/Login.tsx
  client/src/pages/ReviewLists.tsx
  client/src/store/login.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#140 faet: 마이페이지 프로필 이미지 수정 구현
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#142 feat:모달2 작업중
  client/src/App.tsx
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Selectors/CategorieSelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/common.css
  client/src/pages/WriteReview.tsx
  client/src/store/categorie.tsx
Labels: Front, 기능추가

#144 feat: 제품및 리뷰 ResponseDTO 추가 및 일부 로직 수정
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductDto.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/mapper/ProductMapper.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/repository/ProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/ProductRepositoryCustom.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/mapper/ReviewMapper.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/repository/ReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
  server/src/main/java/seb/project/Codetech/user/controller/UserController.java
  server/src/main/java/seb/project/Codetech/user/service/UserService.java
  server/src/test/java/seb/project/Codetech/product/service/ProductServiceTest.java
Labels: Back, 기능추가, 리펙토링

#147 feat:Modal2 기능 추가
  client/src/components/Selectors/ProductSelector.tsx
  client/src/util/useAxios.tsx
Labels: Front, 기능추가

#148 fix: modal2기능 오타 수정
  client/src/components/Selectors/ProductSelector.tsx
  client/src/util/useAxios.tsx
Labels: Front, 수정

#150 feat: 상세 리뷰 조회수 기능 및 리뷰 댓글 상태관리 구현 (#146)
  server/src/main/java/seb/project/Codetech/review/controller/ReviewCommController.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewCommRequestDto.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java
  server/src/main/java/seb/project/Codetech/review/mapper/ReviewMapper.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewCommService.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가, 리펙토링

#152 Feat : 글쓴이 정보 추가, 포인트 추천 리팩토링 #145
  server/src/main/java/seb/project/Codetech/question/service/AnswerService.java
  server/src/main/java/seb/project/Codetech/question/service/QuestionService.java
  server/src/main/java/seb/project/Codetech/recommend/dto/RecommendDto.java
  server/src/main/java/seb/project/Codetech/recommend/service/RecommendService.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewCommService.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
  server/src/main/java/seb/project/Codetech/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
  server/src/main/java/seb/project/Codetech/user/controller/UserController.java
  server/src/main/java/seb/project/Codetech/user/dto/UserAndQuestionsDto.java
  server/src/main/java/seb/project/Codetech/user/dto/UserAndReviewsDto.java
  server/src/main/java/seb/project/Codetech/user/service/UserService.java
  server/src/main/resources/application-dev.yml
Labels: Back, 기능추가, 리펙토링, 수정

#154 Feat : 회원 이미지 비밀번호 닉네임 수정을 분리#145
  server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java
  server/src/main/java/seb/project/Codetech/user/controller/UserController.java
  server/src/main/java/seb/project/Codetech/user/dto/UserPasswordDto.java
  server/src/main/java/seb/project/Codetech/user/service/UserService.java
Labels: Back, 기능추가, 수정

#155 feat: 작성글에 작성자 식별자 추가
  server/src/main/java/seb/project/Codetech/question/dto/QuestionResponseDto.java
  server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
Labels: Back, 기능추가

#160 feat: 마이페이지 프로필 수정 구현
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/store/userInfo.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#161 fix: 제품등록 모달 구현중
  client/package-lock.json
  client/package.json
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/pages/WriteReview.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#163 fix: 제품등록 모달 구현 완료
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#166 feat: product api
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/mapper/ProductMapper.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/repository/ReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가

#168 feat: 파일 업로드 API 기능 구현
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
Labels: Back, 기능추가

#170 feat: product api
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
Labels: Back, 기능추가

#172 fix: 중복 메서드 제거
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
Labels: Back, 수정

#176 feat:토스트에디터 이미지업로드 기능구현 완료
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/pages/WriteReview.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#178 feat: 메인페이지 제품 목록 조회 구현
  server/src/main/java/seb/project/Codetech/event/dto/ReviewUpdateEvent.java
  server/src/main/java/seb/project/Codetech/event/dto/SnackReviewUpdateEvent.java
  server/src/main/java/seb/project/Codetech/event/handler/ProductStatEventHandler.java
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/productstat/entity/ProductStat.java
  server/src/main/java/seb/project/Codetech/productstat/repository/ProductStatRepository.java
  server/src/main/java/seb/project/Codetech/productstat/service/ProductStatService.java
  server/src/main/java/seb/project/Codetech/redis/service/ProductStatService.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
  server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java
  server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
Labels: Back, 기능추가

#179 feat: 마이페이지 리뷰조회 탭 API 연동
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewTabPagenation.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/pages/ReviewLists.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#182 feat: 메인 페이지에서 베스트 리뷰 조회 API 구현
  server/src/main/java/seb/project/Codetech/file/entity/FileEntity.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/mapper/ReviewMapper.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가

#183 fix: 스낵리뷰 유효성 검사 문제 해결
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/productstat/controller/ProductStatController.java
  server/src/main/java/seb/project/Codetech/productstat/dto/ProductStatResponseDto.java
  server/src/main/java/seb/project/Codetech/question/service/AnswerService.java
  server/src/main/java/seb/project/Codetech/redis/config/RedisConfig.java
  server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/snackreview/validation/validator/ScoreValidator.java
Labels: Back, 기능추가

#187 fix: 질문, 답변 응답에서 유저 프로필 이미지 누락된 것 추가 (#186)
  server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java
Labels: Back, 수정

#189 fix: 마이페이지 탭 동작 수정
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/store/userInfo.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#193 fix: 리뷰작성 셀렉터, 모달수정#192
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Selectors/CategorieSelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/pages/WriteReview.tsx
Labels: Front, 수정

#195 feat: 베스트 리뷰 응답 객체 변경.
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
Labels: Back, 기능추가

#201 feat: 리뷰리스트 페이지 수정 모달, 기능 구현
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/components/common.css
  client/src/pages/ReviewLists.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#205 Feat: 질문 page UX 개선
  client/src/components/Modal/Confirm.tsx
  client/src/components/QuestionList/BodyTop.tsx
  client/src/components/QuestionList/Completes.tsx
  client/src/pages/QuestionLists.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#208 feat: refresh 토큰을 사용한 재인증 과정 간소화
  client/src/components/Modal/EditQuestion.tsx
  client/src/components/QuestionList/BodyTop.tsx
  client/src/pages/Signup.tsx
  client/src/util/apiCollection.tsx
  client/src/util/loginRefresh.tsx
Labels: 기능추가, 리펙토링

#209 feat: 베스트 상세리뷰 응답객체 추가 구현
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewCommResponseDto.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
  server/src/main/resources/application-dev.yml
Labels: Back, 기능추가

#210 feat: 리뷰 작성 페이지 포스트 요청 완료 #177
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/pages/WriteReview.tsx
  client/src/store/review.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#214 feat: 상세 리뷰 검색 기능 구현
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
  server/src/main/resources/application-dev.yml
Labels: Back, 기능추가

#215 fix: 일부 오류 로직 수정 (#212)
  server/src/main/java/seb/project/Codetech/product/entity/Type.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
Labels: Back, 수정

#217 feat: 상세 리뷰의 응답 객체 추가 구현
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/resources/application-dev.yml
Labels: Back, 기능추가, 수정

#219 fix: 스낵리뷰 수정기능 수정
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/components/Review/RvSelectBox.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/pages/ReviewLists.tsx
  client/src/types/mainPageTypes.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#220 feat: 상세 리뷰 조회 및 정렬 구현 Merge
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/entity/Sort.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewCommService.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가

#222 feat: 상세 리뷰 검색의 컨트롤러 및 서비스 로직 수정 및 리팩토링
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가, 리펙토링

#224 feat: 제품 검색 페이지 검색 기능 구현
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
Labels: Back, 기능추가

#227 fix: 마이페이지 리뷰리스트 리프레쉬 토큰에러 수정
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#228 feat: 이메일 유효성 검사 #266
  client/src/pages/Signup.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가

#231 fix: 마이페이지 탭 레이아웃 수정
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewTabPagenation.tsx
Labels: Front, 수정

#233 fix: 한줄리뷰 레이아웃, 유저이미지 변경
  client/src/components/Avatar/Avatar.tsx
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/Review/SnackReview.tsx
Labels: Front, 수정

#235 feat: 섬네일 서비스 로직 구현 (#225)
  server/build.gradle
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
Labels: Back, 기능추가

#237 feat: 요청 응답데이터 수정
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
Labels: Back, 기능추가

#239 feat: 리뷰 썸네일 로직 구현
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductDto.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가

#241 feat: 제품의 일부 문제 해결
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/mapper/ProductMapper.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가, 리펙토링

#242 fix: 마이페이지 답글 오류 수정
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/Review/AvgRating.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/pages/ReviewLists.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#243 feat: 리뷰리스트 상세리뷰 API 연동
  client/src/components/MyPage/Profile.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/pages/ReviewLists.tsx
Labels: Front, 기능추가

#244 feat: 썸네일 관련 수정 사항 적용 (#238)
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/entity/FileDto.java
  server/src/main/java/seb/project/Codetech/file/service/FileService.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductDto.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
Labels: Back, 기능추가
