Repository codestates-seb/seb40_main_011, pull requests merged in 2022-12, with the labels that each got.

#247 feat: 썸네일 응답 데이터 처리
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
Labels: Back, 기능추가

#249 fix: 리뷰작성,제품등록 에러해결 #232
  client/src/components/Modal/AddProduct.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/pages/WriteReview.tsx
  client/src/store/categorie.tsx
  client/src/store/review.tsx
  client/src/util/Regex.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#253 feat: main page 레이아웃 및 css, 기능 변경
  client/src/App.tsx
  client/src/components/List/BestReviewList.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/List/QuestionList.tsx
  client/src/components/Oauth/Google.tsx
  client/src/components/Selectors/MainCategory.tsx
  client/src/images/placeholder-image.png
  client/src/pages/Login.tsx
  client/src/types/mainPageTypes.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 기능추가, 레이아웃

#258 style: main page 하단에 질문부분 레이아웃 수정
  client/src/components/List/BestReviewList.tsx
  client/src/components/List/QuestionList.tsx
  client/src/pages/Login.tsx
Labels: Front, 레이아웃

#264 feat: 검증 DTO 구현
  server/src/main/java/seb/project/Codetech/file/controller/FileController.java
  server/src/main/java/seb/project/Codetech/file/entity/FileDto.java
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductListResponse.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductRequestDto.java
  server/src/main/java/seb/project/Codetech/product/mapper/ProductMapper.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepository.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewCommController.java
  server/src/main/java/seb/project/Codetech/review/controller/ReviewController.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewCommRequestDto.java
  server/src/main/java/seb/project/Codetech/review/dto/ReviewRequestDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepository.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 기능추가, 리펙토링

#267 fix: 마이페이지 에러 핸들링
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/MyPage/ReviewTabPagenation.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/components/Review/DetailReview.tsx
Labels: Front, 수정, 에러 핸들링

#272 feat: 제품 등록 오류 수정
  server/src/main/java/seb/project/Codetech/product/dto/ProductRequestDto.java
Labels: Back, 수정

#277 feat: 마이페이지 반응형 CSS적용
  client/src/App.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/pages/MyPage.tsx
Labels: Front, 기능추가, 레이아웃

#279 fix: 리뷰 작성 페이지 수정완료 #262
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Modal/ThumbnailModal.tsx
  client/src/components/Selectors/CategorySelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/components/common.css
  client/src/pages/WriteReview.tsx
  client/src/store/categories.tsx
Labels: Front, 수정

#281 fix: 빌드 에러 해결 #280
  client/src/components/Details/EditReviewDetail.tsx
  client/src/pages/Main.tsx
Labels: Front, 수정

#288 feat: 상세리뷰 조회에서 응답 데이터 추가
  server/build.gradle
  server/src/main/java/seb/project/Codetech/review/dto/ReviewResponseDto.java
  server/src/main/java/seb/project/Codetech/review/repository/CustomReviewRepositoryImpl.java
  server/src/main/resources/application-dev.yml
Labels: Back, 기능추가

#290 feat: 썸네일 관련 기능 추가 및 관련 응답 DTO 수정
  server/src/main/java/seb/project/Codetech/product/controller/ProductController.java
  server/src/main/java/seb/project/Codetech/product/dto/ProductResponseDto.java
  server/src/main/java/seb/project/Codetech/product/entity/Product.java
  server/src/main/java/seb/project/Codetech/product/repository/CustomProductRepositoryImpl.java
  server/src/main/java/seb/project/Codetech/product/service/ProductService.java
Labels: Back, 기능추가, 리펙토링

#294 fix: 리뷰작성 페이지 셀렉터, 리다이렉트 수정 #293
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Selectors/CategorySelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/common.css
  client/src/pages/Signup.tsx
  client/src/pages/WriteReview.tsx
  client/src/store/categories.tsx
Labels: Front, 수정

#298 fix: 회원가입 탈퇴한 회원 에러 핸들링 #295
  client/src/pages/Signup.tsx
Labels: Front, 에러 핸들링

#301 fix: 마이페이지 반응형 수정
  client/src/App.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/layout/Layout.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
Labels: Front, 수정

#304 fix: 회원가입 한글닉네임 에러 해결 #303
  client/src/components/Modal/Confirm.tsx
  client/src/pages/Signup.tsx
Labels: Front, 수정

#306 fix: 마이페이지 모달 알림 방식 변경
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/AnswersMore.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/common.css
  client/src/pages/MyPage.tsx
  client/src/util/apiCollection.tsx
Labels: Front, 수정

#307 fix: 마이페이지 모달 반응형 작업
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/common.css
  client/src/pages/MyPage.tsx
Labels: Front, 레이아웃, 수정

#311 fix: footer copyright 추가
  client/src/components/Avatar/Avatar.tsx
  client/src/components/Details/EditReviewDetail.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/List/QuestionList.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/Review/AvgRating.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/icons/index.tsx
  client/src/pages/ReviewLists.tsx
  client/src/pages/Signup.tsx
Labels: Front, 수정

#312 fix: footer copyright 추가
  client/src/components/Avatar/Avatar.tsx
  client/src/components/Details/EditReviewDetail.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/List/QuestionList.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/Review/AvgRating.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/icons/index.tsx
  client/src/pages/ReviewLists.tsx
  client/src/pages/Signup.tsx
Labels: Front, 수정

#315 feat: 상세 리뷰 관련 서비스 로직 문제 수정
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java
  server/src/main/java/seb/project/Codetech/review/repository/ReviewCommRepository.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 수정, 에러 핸들링

#316 feat: feat: 상세 리뷰 관련 서비스 로직 문제 수정
  server/src/main/java/seb/project/Codetech/review/entity/Review.java
  server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java
  server/src/main/java/seb/project/Codetech/review/repository/ReviewCommRepository.java
  server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
Labels: Back, 수정

#318 Style/kwngmin/review list css #317
  client/src/App.tsx
Labels: Front, 기능추가, 레이아웃, 리펙토링

#320 fix: 리뷰리스트 에러 수정
  client/src/components/Details/EditReviewDetail.tsx
  client/src/components/Review/SnackReview.tsx
Labels: Front, 수정

#330 Style/kwngmin/review list and etc #317
  client/src/App.css
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/Member.tsx
  client/src/components/List/QuestionList.tsx
  client/src/components/Review/AvgRating.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/layout/Layout.tsx
  client/src/pages/ReviewLists.tsx
Labels: Front, 레이아웃, 리펙토링

#339 feat: 렌딩페이지 구현
  client/src/components/MyPage/MypageTab.tsx
  client/src/images/Dec-05-2022 10-35-53.gif
  client/src/images/Dec-05-2022 11-14-13.gif
  client/src/images/Dec-05-2022 14-15-32.gif
  client/src/pages/LandingPage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
Labels: Front, 기능추가, 레이아웃

#341 feat: 렌딩페이지 구현
  client/src/components/MyPage/MypageTab.tsx
  client/src/images/Dec-05-2022 10-35-53.gif
  client/src/images/Dec-05-2022 11-14-13.gif
  client/src/images/Dec-05-2022 14-15-32.gif
  client/src/pages/LandingPage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
Labels: Front, 기능추가, 레이아웃

#336 Feat: kakao login #174
  server/src/main/java/seb/project/Codetech/security/config/SecurityConfig.java
  server/src/main/java/seb/project/Codetech/security/oauth2/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/seb/project/Codetech/security/oauth2/provider/CustomOAuth2Provider.java
  server/src/main/resources/application-dev.yml
Labels: Back, 기능추가

#343 fix: 리뷰작성페이지 반응형
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Modal/ThumbnailModal.tsx
  client/src/components/Selectors/CategorySelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/common.css
  client/src/pages/WriteReview.tsx
Labels: Front, 수정

#345 fix: 리뷰작성페이지 반응형 #308
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Modal/ThumbnailModal.tsx
  client/src/components/Selectors/CategorySelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/common.css
  client/src/pages/WriteReview.tsx
  server/src/main/java/seb/project/Codetech/security/oauth2/provider/CustomOAuth2Provider.java
  server/src/main/resources/application-dev.yml
Labels: Front, 수정

#352 Fix : uri 변경#174
  server/src/main/java/seb/project/Codetech/security/oauth2/provider/CustomOAuth2Provider.java
  server/src/main/java/seb/project/Codetech/user/service/UserService.java
  server/src/main/resources/application-dev.yml
Labels: Back, 수정

#353 Style/kwngmin/review list respondible #346
  client/src/components/List/BestReviewList.tsx
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/components/Review/DetailReview.tsx
Labels: Front, 레이아웃, 리펙토링, 에러 핸들링

#357 fix: 회원가입 이메일인증 팝업추가 #356
  client/src/pages/Signup.tsx
Labels: Front, 수정

#359 style: review list css 상세리뷰 image
  client/src/components/QuestionList/Answer.tsx
  client/src/components/QuestionList/Completes.tsx
  client/src/components/QuestionList/PendingQuestion.tsx
  client/src/components/QuestionList/Question.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/pages/QuestionLists.tsx
Labels: Front, 레이아웃

#360 feat: 리뷰리스트 한줄리뷰 작성 별점 표시기능 추가
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/pages/ReviewLists.tsx
Labels: Front, 기능추가

#363 fix: 리뷰리스트 한줄리뷰 모달 CSS 수정
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/pages/ReviewLists.tsx
Labels: Front, 레이아웃, 수정

#365 feat: 마이페이지 답글 더보기 기능 구현
  client/src/components/MyPage/AnswersMore.tsx
  client/src/components/MyPage/AnswersTab.tsx
Labels: Front, 기능추가

#366 fix: 오타수정
  client/src/components/MyPage/AnswersMore.tsx
  client/src/components/Review/CreateSnackReview.tsx
Labels: Front, 수정

#370 fix: 한줄리뷰 모달 수정
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/pages/Main.tsx
Labels: Front, 수정

#376 style: 리뷰리스트, 리뷰상세, 메인 css 수정
  client/src/components/Details/Comment.tsx
  client/src/components/Details/CommentInput.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/components/Review/DetailReview.tsx
  client/src/components/Review/SnackReview.tsx
  client/src/pages/Main.tsx
  client/src/pages/ReviewLists.tsx
Labels: Front, 레이아웃, 수정

#378 Fix: 토큰 주는 위치 변경 #174
  server/src/main/java/seb/project/Codetech/security/config/SecurityConfig.java
  server/src/main/java/seb/project/Codetech/security/oauth2/entity/Provider.java
  server/src/main/java/seb/project/Codetech/security/oauth2/handler/OAuth2UserSuccessHandler.java
Labels: Back, 수정

#381 fix: 소셜로그인 콘솔 및 질문 답변 페이지 채택에러 수정
  client/src/App.tsx
  client/src/components/Header/Header.tsx
  client/src/components/QuestionList/FirstAnswer.tsx
  client/src/components/QuestionList/Question.tsx
  client/src/pages/Login.tsx
  client/src/pages/SocialLogin.tsx
Labels: Front, 에러 핸들링

#386 Feat: 카카오톡 소셜로그인 기능 추가 및 여러페이지 css, 기능 구현
  client/src/components/Avatar/Avatar.tsx
  client/src/components/Details/CommentInput.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/Review/AvgRating.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/images/placeholder-img-profile.png
  client/src/pages/Login.tsx
Labels: Front, 기능추가, 레이아웃

#387 feat: 다크모드 기능 추가
  client/public/index.html
  client/src/components/Header/DarkMode.tsx
  client/src/components/Header/Header.tsx
  client/src/components/MyPage/AnswersMore.tsx
  client/src/components/MyPage/AnswersTab.tsx
  client/src/components/MyPage/LikeReviewTab.tsx
  client/src/components/MyPage/MypageTab.tsx
  client/src/components/MyPage/Profile.tsx
  client/src/components/MyPage/QuestionsTab.tsx
  client/src/components/MyPage/ReviewsTab.tsx
  client/src/components/MyPage/SnackReviewTab.tsx
  client/src/pages/LandingPage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/ReviewLists.tsx
  client/tailwind.config.js
Labels: Front, 기능추가, 레이아웃

#388 feat&style: 마이페이지 및 회원가입
  client/src/components/MyPage/Profile.tsx
  client/src/pages/Signup.tsx
Labels: Front, 기능추가, 레이아웃

#391 fix: 다크모드 설정 수정
  client/public/index.html
Labels: Front, 수정

#392 style: 리뷰작성,제품추가,썸네일 다크모드 적용 #367
  client/src/components/Header/Header.tsx
  client/src/components/Modal/AddProduct.tsx
  client/src/components/Modal/Confirm.tsx
  client/src/components/Modal/ThumbnailModal.tsx
  client/src/components/Selectors/CategorySelector.tsx
  client/src/components/Selectors/ProductSelector.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/pages/WriteReview.tsx
  client/src/store/darkMode.tsx
  client/tailwind.config.js
Labels: Front, 레이아웃

#393 style: 회원가입 다크모드 적용 #367
  client/src/images/darkmode_logo.png
  client/src/pages/Signup.tsx
Labels: Front, 레이아웃

#394 feat: 마이페이지 한줄리뷰 모달 다크모드 구현
  client/src/components/Modal/EditPassword.tsx
  client/src/components/Modal/EditProfile.tsx
  client/src/components/Modal/EditProfileImg.tsx
  client/src/components/Modal/OptOut.tsx
  client/src/components/Modal/SnackReviewModal.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/components/common.css
Labels: Front, 기능추가, 레이아웃

#400 fix: 다크모드 수정
  client/src/components/Header/Header.tsx
Labels: Front, 수정

#405 style: 로그인, 로그아웃 다크모드 수정 #367
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
Labels: Front, 레이아웃, 수정

#406 style: 토스트 에디터 다크모드 수정 #367
  client/src/components/ToastUI/TextEditor.tsx
Labels: Front, 레이아웃, 수정

#408 Style: 리뷰 디테일 다크모드 적용, 기타 레이아웃 수정 및 보완
  client/src/components/Details/Comment.tsx
  client/src/components/Details/CommentInput.tsx
  client/src/components/Details/RvDetail.tsx
  client/src/components/Header/SearchBar.tsx
  client/src/components/List/ProductList.tsx
  client/src/components/Review/CreateSnackReview.tsx
  client/src/components/Review/RvSelectBox.tsx
  client/src/components/Selectors/MainCategory.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
Labels: Front, 레이아웃

#414 fix: 리뷰리스트 더보기 CSS수정
  client/src/pages/ReviewLists.tsx
Labels: Front, 수정
